// Code generated by digen; DO NOT EDIT.

//go:generate go run -mod=mod github.com/shanjunmei/dig/cmd/digen  -debug=false -unused=ignore -alias=full -inline=true -out=dig_gen.go
//go:build !digen
// +build !digen

package supply_param

import (
	"context"
	"github.com/shanjunmei/dig/example/supply_param_helper"
)

func InitSupplyParam(cfg *supply_param_helper.Config) func(context.Context) error {
	dv0 := cfg
	_ = cfg
	return func(ctx context.Context) error {
		func(c *supply_param_helper.Config) {
			_ = c
		}(dv0)
		return nil
	}
}
