// Package di provides marker functions and optional runtime for dependency injection.
package dig

import "context"

// Option is the interface that all DI options implement.
// It is sealed by the private method `isOption()` to prevent external implementations.
type Option interface {
	isOption()
}

// Provide registers one or more constructors.
func Provide(constructors ...any) Option {
	panic("dig: Provide stub called; run go generate to generate wiring code")
}

// Invoke registers one or more functions.
func Invoke(functions ...any) Option {
	panic("dig: Invoke stub called; run go generate to generate wiring code")
}

// Supply directly provides one or more values.
func Supply(values ...any) Option {
	panic("dig: Supply stub called; run go generate to generate wiring code")
}

// Module combines multiple options.
func Module(opts ...Option) Option {
	panic("dig: Module stub called; run go generate to generate wiring code")
}

// Build is the entry point for code generation. It takes a list of Options
// and returns an App. The actual implementation is generated by digen.
func Build(opts ...Option) func(context.Context) error {
	// This function is replaced by generated code.
	panic("dig: Build called but code not generated; run go generate")
}
