// Code generated by digen; DO NOT EDIT.

//go:generate go run -mod=mod github.com/shanjunmei/dig/cmd/digen
//go:build !digen
// +build !digen

package main

import (
	"context"
	"github.com/shanjunmei/dig/internal/app"
	"github.com/shanjunmei/dig/internal/config"
	"github.com/shanjunmei/dig/internal/generator"
	"github.com/shanjunmei/dig/internal/loader"
	"github.com/shanjunmei/dig/internal/logger"
	"github.com/shanjunmei/dig/internal/processor"
	"github.com/shanjunmei/dig/pkg/alias"
	"log"
)

func dig_provider_1(_cfg *config.Config) string {
	return _cfg.AliasType
}
func dig_provider_2(_aliasType string) alias.AliasStrategy {
	aliasType, err := alias.ParseAliasType(_aliasType)
	if err != nil {
		log.Fatalln(err)
	}
	return alias.NewAliasStrategy(aliasType)
}
func dig_invoke_1(a *app.App) error {
	return a.Run()
}

func InitApp(cfg *config.Config) func(context.Context) error {
	v0 := cfg
	v1 := loader.NewPackageLoader()
	v2 := logger.NewLogger(v0)
	v3 := dig_provider_1(v0)
	v4 := generator.NewGenerator(v2, v0)
	v5 := dig_provider_2(v3)
	v6 := processor.NewProcessor(v1, v4, v2, v0)
	v7 := app.NewApp(v6, v1, v2, v5, v0)
	return func(ctx context.Context) error {
		if err := dig_invoke_1(v7); err != nil {
			return err
		}
		return nil
	}
}
