// Code generated by digen; DO NOT EDIT.

//go:generate go run -mod=mod github.com/shanjunmei/dig/cmd/digen  -debug=false -unused=ignore -alias=full -inline=true -out=dig_gen.go
//go:build !digen
// +build !digen

package main

import (
	"context"
	"github.com/shanjunmei/dig/internal/app"
	"github.com/shanjunmei/dig/internal/config"
	"github.com/shanjunmei/dig/internal/generator"
	"github.com/shanjunmei/dig/internal/loader"
	"github.com/shanjunmei/dig/internal/logger"
	"github.com/shanjunmei/dig/internal/processor"
	"github.com/shanjunmei/dig/pkg/alias"
	"log"
)

func dig_provider_2(_aliasType string) alias.AliasStrategy {
	aliasType, err := alias.ParseAliasType(_aliasType)
	if err != nil {
		log.Fatalln(err)
	}
	return alias.NewAliasStrategy(aliasType)
}

func InitApp(cfg *config.Config) func(context.Context) error {
	dv0 := cfg
	dv1 := loader.NewPackageLoader()
	dv2 := logger.NewLogger(dv0)
	dv3 := func(_cfg *config.Config) string {
		return _cfg.AliasType
	}(dv0)
	dv4 := generator.NewGenerator(dv2, dv0)
	dv5 := dig_provider_2(dv3)
	dv6 := processor.NewProcessor(dv1, dv4, dv2, dv0)
	dv7 := app.NewApp(dv6, dv1, dv2, dv5, dv0)
	return func(ctx context.Context) error {
		if err := func(a *app.App) error {
			return a.Run()
		}(dv7); err != nil {
			return err
		}
		return nil
	}
}
