// Code generated by digen; DO NOT EDIT.

//go:generate go run -mod=mod github.com/shanjunmei/dig/cmd/digen  -debug=false -unused=ignore -alias=full -inline=true -out=dig_gen.go
//go:build !digen
// +build !digen

package closure_capture_timehour

import (
	"context"
	"time"
)

func InitCaptureTimeHour() func(context.Context) error {
	dv0 := NewConfig()
	return func(ctx context.Context) error {
		func(cfg *Config) {
			cfg.Interval = 24 * time.Hour
		}(dv0)
		return nil
	}
}
