// Code generated by digen; DO NOT EDIT.

//go:generate go run -mod=mod github.com/shanjunmei/dig/cmd/digen
//go:build !digen
// +build !digen

package main

import (
	"context"
	"github.com/shanjunmei/dig/internal/app"
	"github.com/shanjunmei/dig/internal/config"
	"github.com/shanjunmei/dig/internal/generator"
	"github.com/shanjunmei/dig/internal/loader"
	"github.com/shanjunmei/dig/internal/logger"
	"github.com/shanjunmei/dig/internal/processor"
	"github.com/shanjunmei/dig/pkg/alias"
	"log"
)

var Logf = log.Printf

func dig_provider_1(_cfg *config.Config) string {
	return _cfg.AliasType
}
func dig_provider_2(_aliasType string) alias.AliasStrategy {
	aliasType, err := alias.ParseAliasType(_aliasType)
	if err != nil {
		log.Fatalln(err)
	}
	return alias.NewAliasStrategy(aliasType)
}
func dig_invoke_1(a *app.App) error {
	return a.Run()
}

func InitApp(cfg *config.Config) func(context.Context) error {
	Logf("[SUPPLY] before: %s\n", "*github.com/shanjunmei/dig/internal/config.Config")
	// external parameter cfg (type *github.com/shanjunmei/dig/internal/config.Config) from cmd/digenv2/di.go:21
	v0 := cfg
	Logf("[SUPPLY] after: %s\n", "*github.com/shanjunmei/dig/internal/config.Config")
	Logf("[PROVIDE] before: %s\n", "github.com/shanjunmei/dig/internal/loader.NewPackageLoader")
	v1 := loader.NewPackageLoader()
	Logf("[PROVIDE] after: %s\n", "github.com/shanjunmei/dig/internal/loader.NewPackageLoader")
	Logf("[PROVIDE] before: %s\n", "github.com/shanjunmei/dig/internal/logger.NewLogger")
	v2 := logger.NewLogger(v0)
	Logf("[PROVIDE] after: %s\n", "github.com/shanjunmei/dig/internal/logger.NewLogger")
	Logf("[PROVIDE] before: %s\n", "github.com/shanjunmei/dig/cmd/digenv2.dig_provider_1")
	v3 := dig_provider_1(v0)
	Logf("[PROVIDE] after: %s\n", "github.com/shanjunmei/dig/cmd/digenv2.dig_provider_1")
	Logf("[PROVIDE] before: %s\n", "github.com/shanjunmei/dig/internal/generator.NewGenerator")
	v4 := generator.NewGenerator(v2, v0)
	Logf("[PROVIDE] after: %s\n", "github.com/shanjunmei/dig/internal/generator.NewGenerator")
	Logf("[PROVIDE] before: %s\n", "github.com/shanjunmei/dig/cmd/digenv2.dig_provider_2")
	v5 := dig_provider_2(v3)
	Logf("[PROVIDE] after: %s\n", "github.com/shanjunmei/dig/cmd/digenv2.dig_provider_2")
	Logf("[PROVIDE] before: %s\n", "github.com/shanjunmei/dig/internal/processor.NewProcessor")
	v6 := processor.NewProcessor(v1, v4, v2, v0)
	Logf("[PROVIDE] after: %s\n", "github.com/shanjunmei/dig/internal/processor.NewProcessor")
	Logf("[PROVIDE] before: %s\n", "github.com/shanjunmei/dig/internal/app.NewApp")
	v7 := app.NewApp(v6, v1, v2, v5, v0)
	Logf("[PROVIDE] after: %s\n", "github.com/shanjunmei/dig/internal/app.NewApp")
	return func(ctx context.Context) error {
		Logf("[INVOKE] before: %s\n", "github.com/shanjunmei/dig/cmd/digenv2.dig_invoke_1")
		if err := dig_invoke_1(v7); err != nil {
			Logf("[INVOKE] failed: %s: %v\n", "github.com/shanjunmei/dig/cmd/digenv2.dig_invoke_1", err)
			return err
		}
		Logf("[INVOKE] after: %s\n", "github.com/shanjunmei/dig/cmd/digenv2.dig_invoke_1")
		return nil
	}
}
