// Code generated by digen; DO NOT EDIT.

//go:generate go run -mod=mod github.com/shanjunmei/dig/cmd/digen  -debug=false -unused=drop -alias=full -inline=false -out=dig_gen.go
//go:build !digen
// +build !digen

package app_basic

import (
	"context"
	"fmt"
	"github.com/shanjunmei/dig/example/common"
	"github.com/shanjunmei/dig/example/internal/logger"
	"github.com/shanjunmei/dig/example/role"
	role_repository "github.com/shanjunmei/dig/example/role/repository"
	"github.com/shanjunmei/dig/example/user"
	"github.com/shanjunmei/dig/example/user/repository"
)

func dig_provider_1() (str string, err error) {
	str = "user-module"
	return
}

func dig_invoke_1(r *repository.Repository[string]) {
	r.Print()
}

func dig_invoke_2(r *role_repository.Repository[int]) {
	r.Add(42)
	r.Print()
}

func dig_invoke_3(cfg role.Config) {
	fmt.Printf("Config supplied: %s\n", cfg)
}

func dig_invoke_4(s *role.Server) {
	s.Run()
}

func dig_invoke_5(str string, cfg *common.Config, log *logger.Logger) error {
	log.Println("Basic:", str, "on port", cfg.Port)
	return nil
}

func InitAppBasic(cfg *common.Config, log *logger.Logger) func(context.Context) error {
	v0 := cfg
	v1 := log
	v2 := user.NewStore[int]()
	v3 := repository.NewRepository[string]()
	v4, err := dig_provider_1()
	if err != nil {
		panic(err)
	}
	v5 := 100
	v6 := role_repository.NewRepository[int]()
	v7 := role.Config("production")
	v8 := role.NewServer(v5)
	return func(ctx context.Context) error {
		dig_invoke_1(v3)
		if err := user.ProcessStore[int](v2, v4); err != nil {
			return err
		}
		dig_invoke_2(v6)
		dig_invoke_3(v7)
		dig_invoke_4(v8)
		if err := dig_invoke_5(v4, v0, v1); err != nil {
			return err
		}
		return nil
	}
}
