// Code generated by digen; DO NOT EDIT.

//go:generate go run -mod=mod github.com/shanjunmei/dig/cmd/digen  -debug=true -unused=error -alias=full -inline=true -out=dig_gen.go
//go:build !digen
// +build !digen

package app_basic

import (
	"context"
	"fmt"
	"github.com/shanjunmei/dig/example/common"
	"github.com/shanjunmei/dig/example/internal/logger"
	"github.com/shanjunmei/dig/example/role"
	role_repository "github.com/shanjunmei/dig/example/role/repository"
	"github.com/shanjunmei/dig/example/user"
	"github.com/shanjunmei/dig/example/user/repository"
	"log"
)

var Logf = log.Printf

// original package: github.com/shanjunmei/dig/example/user
// closure defined at example/user/module.go:12
func dig_provider_1() (str string, err error) {
	str = "user-module"
	return
}

// original package: github.com/shanjunmei/dig/example/role/repository
// closure defined at example/role/repository/module.go:8
func dig_invoke_2(r *role_repository.Repository[int]) {
	r.Add(42)
	r.Print()
}

// closure defined at example/app_basic/di.go:21
func dig_invoke_5(str string, cfg *common.Config, log *logger.Logger) error {
	log.Println("Basic:", str, "on port", cfg.Port)
	return nil
}

func InitAppBasic(cfg *common.Config, log *logger.Logger) func(context.Context) error {
	Logf("[SUPPLY] before: %s\n", "*github.com/shanjunmei/dig/example/common.Config")
	// supplied from function 'InitAppBasic' argument 'cfg' (type *github.com/shanjunmei/dig/example/common.Config) at example/app_basic/di.go:17
	v0 := cfg
	Logf("[SUPPLY] after: %s\n", "*github.com/shanjunmei/dig/example/common.Config")
	Logf("[SUPPLY] before: %s\n", "*github.com/shanjunmei/dig/example/internal/logger.Logger")
	// supplied from function 'InitAppBasic' argument 'log' (type *github.com/shanjunmei/dig/example/internal/logger.Logger) at example/app_basic/di.go:17
	v1 := log
	Logf("[SUPPLY] after: %s\n", "*github.com/shanjunmei/dig/example/internal/logger.Logger")
	Logf("[PROVIDE] before: %s\n", "github.com/shanjunmei/dig/example/user.NewStore")
	v2 := user.NewStore[int]()
	Logf("[PROVIDE] after: %s\n", "github.com/shanjunmei/dig/example/user.NewStore")
	Logf("[PROVIDE] before: %s\n", "github.com/shanjunmei/dig/example/user/repository.NewRepository")
	v3 := repository.NewRepository[string]()
	Logf("[PROVIDE] after: %s\n", "github.com/shanjunmei/dig/example/user/repository.NewRepository")
	Logf("[PROVIDE] before: %s\n", "github.com/shanjunmei/dig/example/app_basic.dig_provider_1")
	v4, err := dig_provider_1()
	if err != nil {
		Logf("[PROVIDE] failed: %s: %v\n", "github.com/shanjunmei/dig/example/app_basic.dig_provider_1", err)
		panic(err)
	}
	Logf("[PROVIDE] after: %s\n", "github.com/shanjunmei/dig/example/app_basic.dig_provider_1")
	Logf("[SUPPLY] before: %s\n", "int")
	// supply from github.com/shanjunmei/dig/example/role at example/role/module.go:14
	v5 := 100
	Logf("[SUPPLY] after: %s\n", "int")
	Logf("[PROVIDE] before: %s\n", "github.com/shanjunmei/dig/example/role/repository.NewRepository")
	v6 := role_repository.NewRepository[int]()
	Logf("[PROVIDE] after: %s\n", "github.com/shanjunmei/dig/example/role/repository.NewRepository")
	Logf("[SUPPLY] before: %s\n", "github.com/shanjunmei/dig/example/role.Config")
	// supply from github.com/shanjunmei/dig/example/role at example/role/module.go:16
	v7 := role.Config("production")
	Logf("[SUPPLY] after: %s\n", "github.com/shanjunmei/dig/example/role.Config")
	Logf("[PROVIDE] before: %s\n", "github.com/shanjunmei/dig/example/role.NewServer")
	v8 := role.NewServer(v5)
	Logf("[PROVIDE] after: %s\n", "github.com/shanjunmei/dig/example/role.NewServer")
	return func(ctx context.Context) error {
		Logf("[INVOKE] before: %s\n", "github.com/shanjunmei/dig/example/app_basic.dig_invoke_1")
		func(r *repository.Repository[string]) {
			r.Print()
		}(v3)
		Logf("[INVOKE] after: %s\n", "github.com/shanjunmei/dig/example/app_basic.dig_invoke_1")
		Logf("[INVOKE] before: %s\n", "github.com/shanjunmei/dig/example/user.ProcessStore")
		if err := user.ProcessStore[int](v2, v4); err != nil {
			Logf("[INVOKE] failed: %s: %v\n", "github.com/shanjunmei/dig/example/user.ProcessStore", err)
			return err
		}
		Logf("[INVOKE] after: %s\n", "github.com/shanjunmei/dig/example/user.ProcessStore")
		Logf("[INVOKE] before: %s\n", "github.com/shanjunmei/dig/example/app_basic.dig_invoke_2")
		dig_invoke_2(v6)
		Logf("[INVOKE] after: %s\n", "github.com/shanjunmei/dig/example/app_basic.dig_invoke_2")
		Logf("[INVOKE] before: %s\n", "github.com/shanjunmei/dig/example/app_basic.dig_invoke_3")
		func(cfg role.Config) {
			fmt.Printf("Config supplied: %s\n", cfg)
		}(v7)
		Logf("[INVOKE] after: %s\n", "github.com/shanjunmei/dig/example/app_basic.dig_invoke_3")
		Logf("[INVOKE] before: %s\n", "github.com/shanjunmei/dig/example/app_basic.dig_invoke_4")
		func(s *role.Server) {
			s.Run()
		}(v8)
		Logf("[INVOKE] after: %s\n", "github.com/shanjunmei/dig/example/app_basic.dig_invoke_4")
		Logf("[INVOKE] before: %s\n", "github.com/shanjunmei/dig/example/app_basic.dig_invoke_5")
		if err := dig_invoke_5(v4, v0, v1); err != nil {
			Logf("[INVOKE] failed: %s: %v\n", "github.com/shanjunmei/dig/example/app_basic.dig_invoke_5", err)
			return err
		}
		Logf("[INVOKE] after: %s\n", "github.com/shanjunmei/dig/example/app_basic.dig_invoke_5")
		return nil
	}
}
