// Code generated by digen; DO NOT EDIT.

//go:generate go run -mod=mod github.com/shanjunmei/dig/cmd/digen  -debug=false -unused=ignore -alias=full -inline=true -out=dig_gen.go
//go:build !digen
// +build !digen

package app_basic

import (
	"context"
	"fmt"
	"github.com/shanjunmei/dig/example/common"
	"github.com/shanjunmei/dig/example/internal/logger"
	"github.com/shanjunmei/dig/example/role"
	role_repository "github.com/shanjunmei/dig/example/role/repository"
	"github.com/shanjunmei/dig/example/user"
	"github.com/shanjunmei/dig/example/user/repository"
)

func dig_provider_1() (str string, err error) {
	str = "user-module"
	return
}

func dig_invoke_2(r *role_repository.Repository[int]) {
	r.Add(42)
	r.Print()
}

func dig_invoke_5(str string, cfg *common.Config, log *logger.Logger) error {
	log.Println("Basic:", str, "on port", cfg.Port)
	return nil
}

func InitAppBasic(cfg *common.Config, log *logger.Logger) func(context.Context) error {
	dv0 := cfg
	dv1 := log
	dv2 := user.NewStore[int]()
	dv3 := repository.NewRepository[string]()
	dv4, err := dig_provider_1()
	if err != nil {
		panic(err)
	}
	dv5 := 100
	dv6 := role_repository.NewRepository[int]()
	dv7 := role.Config("production")
	dv8 := role.NewServer(dv5)
	return func(ctx context.Context) error {
		func(r *repository.Repository[string]) {
			r.Print()
		}(dv3)
		if err := user.ProcessStore[int](dv2, dv4); err != nil {
			return err
		}
		dig_invoke_2(dv6)
		func(cfg role.Config) {
			fmt.Printf("Config supplied: %s\n", cfg)
		}(dv7)
		func(s *role.Server) {
			s.Run()
		}(dv8)
		if err := dig_invoke_5(dv4, dv0, dv1); err != nil {
			return err
		}
		return nil
	}
}
