// Code generated by digen; DO NOT EDIT.

//go:generate go run -mod=mod github.com/shanjunmei/dig/cmd/digen  -debug=false -unused=ignore -alias=full -inline=true -out=dig_gen.go
//go:build !digen
// +build !digen

package closure_scope_locals

import (
	"context"
)

func dig_provider_1() *Repo {
	xs := []int{1, 2, 3}
	s := 0
	for i, v := range xs {
		s += v * i
	}
	f := func(x int) int { return x * 2 }
	s += f(s)
	g := func() int {
		inner := 10
		return inner
	}
	s += g()
	var anyv any = s
	switch t := anyv.(type) {
	case int:
		s += t
	}
	if half := s / 2; half > 0 {
		s += half
	}
	return &Repo{N: s}
}

func dig_provider_2() (r *Named) {
	r = &Named{V: 7}
	return
}

func dig_invoke_1(repo *Repo, r *Named) error {
	_, _ = repo, r
	return nil
}

func InitScopeLocals() func(context.Context) error {
	dv0 := dig_provider_1()
	dv1 := dig_provider_2()
	return func(ctx context.Context) error {
		if err := dig_invoke_1(dv0, dv1); err != nil {
			return err
		}
		return nil
	}
}
