// Code generated by digen; DO NOT EDIT.

//go:generate go run -mod=mod github.com/shanjunmei/dig/cmd/digen  -debug=false -unused=ignore -alias=full -inline=true -out=dig_gen.go
//go:build !digen
// +build !digen

package app_runtime_err

import (
	"context"
	"fmt"
	"github.com/shanjunmei/dig/example/common"
)

func dig_provider_1(cfg *common.Config) (enhanced *EnhancedService, err error) {
	if cfg.Port == 0 {
		return nil, fmt.Errorf("port must not be zero")
	}
	return &EnhancedService{Addr: cfg.Addr, Port: cfg.Port}, nil
}

func InitRuntimeErr() func(context.Context) error {
	dv0 := &common.Config{Addr: "localhost", Port: 8080}
	dv1, err := NewService()
	if err != nil {
		panic(err)
	}
	dv2, err := dig_provider_1(dv0)
	if err != nil {
		panic(err)
	}
	return func(ctx context.Context) error {
		if err := func(svc *Service, enhanced *EnhancedService) error {
			return fmt.Errorf("invoke intentionally returned error: svc=%s enhanced=%s:%d",
				svc.Name, enhanced.Addr, enhanced.Port)
		}(dv1, dv2); err != nil {
			return err
		}
		return nil
	}
}
