// Code generated by digen; DO NOT EDIT.

//go:generate go run -mod=mod github.com/shanjunmei/dig/cmd/digen  -debug=true -unused=drop -alias=full -inline=true -out=dig_gen.go
//go:build !digen
// +build !digen

package app_debug

import (
	"context"
	"fmt"
	"github.com/shanjunmei/dig/example/cache"
	"github.com/shanjunmei/dig/example/common"
	"github.com/shanjunmei/dig/example/db"
	"github.com/shanjunmei/dig/example/internal/logger"
	"github.com/shanjunmei/dig/example/role"
	role_repository "github.com/shanjunmei/dig/example/role/repository"
	"github.com/shanjunmei/dig/example/setup"
	"github.com/shanjunmei/dig/example/user"
	"github.com/shanjunmei/dig/example/user/repository"
	"log"
)

var Logf = log.Printf

// original package: github.com/shanjunmei/dig/example/user
// closure defined at module.go:12
func dig_provider_1() (str string, err error) {
	str = "user-module"
	return
}

// original package: github.com/shanjunmei/dig/example/db
// closure defined at module.go:14
func dig_provider_3() (primaryDB *db.DB, err error) {
	primaryDB = &db.DB{Name: "primary", DSN: "postgres://primary:5432/app"}
	return
}

// original package: github.com/shanjunmei/dig/example/db
// closure defined at module.go:19
func dig_provider_4() (replicaDB *db.DB, err error) {
	replicaDB = &db.DB{Name: "replica", DSN: "postgres://replica:5432/app"}
	return
}

// original package: github.com/shanjunmei/dig/example/db
// closure defined at module.go:25
func dig_provider_5() (userRedis *db.RedisClient) {
	userRedis = &db.RedisClient{Name: "user", Address: "redis://user:6379"}
	return
}

// original package: github.com/shanjunmei/dig/example/db
// closure defined at module.go:30
func dig_provider_6() (sessionRedis *db.RedisClient) {
	sessionRedis = &db.RedisClient{Name: "session", Address: "redis://session:6379"}
	return
}

// original package: github.com/shanjunmei/dig/example/setup
// closure defined at full.go:36
func dig_provider_7() *user.Store[string] {
	s := user.NewStore[string]()
	s.Add("hello")
	s.Add("world")
	return s
}

// original package: github.com/shanjunmei/dig/example/setup
// closure defined at full.go:68
func dig_provider_12() (closureDB *db.DB) {
	return &db.DB{Name: "inmem", DSN: "mem://"}
}

// original package: github.com/shanjunmei/dig/example/role/repository
// closure defined at module.go:8
func dig_invoke_2(r *role_repository.Repository[int]) {
	r.Add(42)
	r.Print()
}

// original package: github.com/shanjunmei/dig/example/cache
// closure defined at module.go:23
func dig_invoke_5(stringCache *cache.Cache[string], intCache *cache.Cache[int]) {
	stringCache.Set("greeting", "hello")
	intCache.Set("count", 42)
	fmt.Println("Cache module:")
	stringCache.Print()
	intCache.Print()
}

// original package: github.com/shanjunmei/dig/example/db
// closure defined at module.go:36
func dig_invoke_6(primaryDB *db.DB, userRedis *db.RedisClient, Index db.RedisDbIndex) {
	primaryDB.Ping()
	userRedis.Ping(Index)
}

// original package: github.com/shanjunmei/dig/example/setup
// closure defined at full.go:76
func dig_invoke_8(primaryDB *db.DB, userRedis *db.RedisClient, Index db.RedisDbIndex) {
	primaryDB.Ping()
	userRedis.Ping(Index)
}

// original package: github.com/shanjunmei/dig/example/setup
// closure defined at full.go:82
func dig_invoke_9(pinger db.Pinger, raw any, setupCfg *common.Config, dbVal db.DB, closureDB *db.DB) {
	pinger.Ping()
	if d, ok := raw.(*db.DB); ok {
		d.Ping()
	}
	_ = setupCfg.Port
	_ = dbVal.Name
	closureDB.Ping()
}

// closure defined at di.go:26
func dig_invoke_12(s *user.Store[string], cfg *common.Config, log *logger.Logger) error {
	log.Println("Debug App Invoke: store len =", len(s.GetAll()))
	return nil
}

// closure defined at di.go:31
func dig_invoke_13(stringCache *cache.Cache[string]) {
	stringCache.Set("from-debug", "cross-package")
	stringCache.Print()
}

func InitAppDebug(cfg *common.Config, log *logger.Logger) func(context.Context) error {
	Logf("[SUPPLY] before: %s\n", "*github.com/shanjunmei/dig/example/common.Config")
	// supplied from function 'InitAppDebug' argument 'cfg' (type *github.com/shanjunmei/dig/example/common.Config) at di.go:20
	v0 := cfg
	Logf("[SUPPLY] after: %s\n", "*github.com/shanjunmei/dig/example/common.Config")
	Logf("[SUPPLY] before: %s\n", "*github.com/shanjunmei/dig/example/internal/logger.Logger")
	// supplied from function 'InitAppDebug' argument 'log' (type *github.com/shanjunmei/dig/example/internal/logger.Logger) at di.go:20
	v1 := log
	Logf("[SUPPLY] after: %s\n", "*github.com/shanjunmei/dig/example/internal/logger.Logger")
	Logf("[PROVIDE] before: %s\n", "github.com/shanjunmei/dig/example/user.NewStore")
	v2 := user.NewStore[int]()
	Logf("[PROVIDE] after: %s\n", "github.com/shanjunmei/dig/example/user.NewStore")
	Logf("[PROVIDE] before: %s\n", "github.com/shanjunmei/dig/example/user/repository.NewRepository")
	v3 := repository.NewRepository[string]()
	Logf("[PROVIDE] after: %s\n", "github.com/shanjunmei/dig/example/user/repository.NewRepository")
	Logf("[PROVIDE] before: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_provider_1")
	v4, err := dig_provider_1()
	if err != nil {
		Logf("[PROVIDE] failed: %s: %v\n", "github.com/shanjunmei/dig/example/app_debug.dig_provider_1", err)
		panic(err)
	}
	Logf("[PROVIDE] after: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_provider_1")
	Logf("[SUPPLY] before: %s\n", "int")
	// supply from github.com/shanjunmei/dig/example/role at module.go:14
	v5 := 100
	Logf("[SUPPLY] after: %s\n", "int")
	Logf("[PROVIDE] before: %s\n", "github.com/shanjunmei/dig/example/role/repository.NewRepository")
	v6 := role_repository.NewRepository[int]()
	Logf("[PROVIDE] after: %s\n", "github.com/shanjunmei/dig/example/role/repository.NewRepository")
	Logf("[SUPPLY] before: %s\n", "github.com/shanjunmei/dig/example/role.Config")
	// supply from github.com/shanjunmei/dig/example/role at module.go:16
	v7 := role.Config("production")
	Logf("[SUPPLY] after: %s\n", "github.com/shanjunmei/dig/example/role.Config")
	Logf("[PROVIDE] before: %s\n", "github.com/shanjunmei/dig/example/cache.NewCache")
	v8 := cache.NewCache[string]()
	Logf("[PROVIDE] after: %s\n", "github.com/shanjunmei/dig/example/cache.NewCache")
	Logf("[PROVIDE] before: %s\n", "github.com/shanjunmei/dig/example/cache.NewCache")
	v9 := cache.NewCache[int]()
	Logf("[PROVIDE] after: %s\n", "github.com/shanjunmei/dig/example/cache.NewCache")
	Logf("[SUPPLY] before: %s\n", "github.com/shanjunmei/dig/example/db.RedisDbIndex")
	// supply from github.com/shanjunmei/dig/example/db at module.go:11
	v11 := db.Index
	Logf("[SUPPLY] after: %s\n", "github.com/shanjunmei/dig/example/db.RedisDbIndex")
	Logf("[PROVIDE] before: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_provider_3")
	v12, err := dig_provider_3()
	if err != nil {
		Logf("[PROVIDE] failed: %s: %v\n", "github.com/shanjunmei/dig/example/app_debug.dig_provider_3", err)
		panic(err)
	}
	Logf("[PROVIDE] after: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_provider_3")
	Logf("[PROVIDE] before: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_provider_4")
	v13, err := dig_provider_4()
	if err != nil {
		Logf("[PROVIDE] failed: %s: %v\n", "github.com/shanjunmei/dig/example/app_debug.dig_provider_4", err)
		panic(err)
	}
	Logf("[PROVIDE] after: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_provider_4")
	Logf("[PROVIDE] before: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_provider_5")
	v14 := dig_provider_5()
	Logf("[PROVIDE] after: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_provider_5")
	Logf("[PROVIDE] before: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_provider_6")
	v15 := dig_provider_6()
	Logf("[PROVIDE] after: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_provider_6")
	Logf("[PROVIDE] before: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_provider_7")
	v16 := dig_provider_7()
	Logf("[PROVIDE] after: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_provider_7")
	Logf("[PROVIDE] before: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_provider_10")
	v17 := func() common.Config {
		return common.Config{Addr: "127.0.0.1", Port: 9000}
	}()
	Logf("[PROVIDE] after: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_provider_10")
	Logf("[PROVIDE] before: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_provider_12")
	v18 := dig_provider_12()
	Logf("[PROVIDE] after: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_provider_12")
	Logf("[PROVIDE] before: %s\n", "github.com/shanjunmei/dig/example/role.NewServer")
	v20 := role.NewServer(v5)
	Logf("[PROVIDE] after: %s\n", "github.com/shanjunmei/dig/example/role.NewServer")
	Logf("[PROVIDE] identity conversion: %s -> %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_provider_8", "db.Pinger")
	v21 := db.Pinger(v12)
	Logf("[PROVIDE] after: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_provider_8")
	Logf("[PROVIDE] identity conversion: %s -> %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_provider_9", "any")
	v22 := any(v12)
	Logf("[PROVIDE] after: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_provider_9")
	Logf("[PROVIDE] identity conversion: %s -> %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_provider_11", "*common.Config")
	v23 := &v17
	Logf("[PROVIDE] after: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_provider_11")
	Logf("[PROVIDE] identity conversion: %s -> %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_provider_13", "db.DB")
	v24 := *v18
	Logf("[PROVIDE] after: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_provider_13")
	return func(ctx context.Context) error {
		Logf("[INVOKE] before: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_invoke_1")
		func(r *repository.Repository[string]) {
			r.Print()
		}(v3)
		Logf("[INVOKE] after: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_invoke_1")
		Logf("[INVOKE] before: %s\n", "github.com/shanjunmei/dig/example/user.ProcessStore")
		if err := user.ProcessStore[int](v2, v4); err != nil {
			Logf("[INVOKE] failed: %s: %v\n", "github.com/shanjunmei/dig/example/user.ProcessStore", err)
			return err
		}
		Logf("[INVOKE] after: %s\n", "github.com/shanjunmei/dig/example/user.ProcessStore")
		Logf("[INVOKE] before: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_invoke_2")
		dig_invoke_2(v6)
		Logf("[INVOKE] after: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_invoke_2")
		Logf("[INVOKE] before: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_invoke_3")
		func(cfg role.Config) {
			fmt.Printf("Config supplied: %s\n", cfg)
		}(v7)
		Logf("[INVOKE] after: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_invoke_3")
		Logf("[INVOKE] before: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_invoke_4")
		func(s *role.Server) {
			s.Run()
		}(v20)
		Logf("[INVOKE] after: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_invoke_4")
		Logf("[INVOKE] before: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_invoke_5")
		dig_invoke_5(v8, v9)
		Logf("[INVOKE] after: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_invoke_5")
		Logf("[INVOKE] before: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_invoke_6")
		dig_invoke_6(v12, v14, v11)
		Logf("[INVOKE] after: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_invoke_6")
		Logf("[INVOKE] before: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_invoke_7")
		func(replicaDB *db.DB, sessionRedis *db.RedisClient) {
			fmt.Printf("Replica: %s, Session: %s\n", replicaDB.Name, sessionRedis.Name)
		}(v13, v15)
		Logf("[INVOKE] after: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_invoke_7")
		Logf("[INVOKE] before: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_invoke_8")
		dig_invoke_8(v12, v14, v11)
		Logf("[INVOKE] after: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_invoke_8")
		Logf("[INVOKE] before: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_invoke_9")
		dig_invoke_9(v21, v22, v23, v24, v18)
		Logf("[INVOKE] after: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_invoke_9")
		Logf("[INVOKE] before: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_invoke_10")
		func(s *user.Store[string], cfg *common.Config) {
			if cfg.Port > 8000 {
				s.Add("high-port")
			} else {
				s.Add("low-port")
			}
		}(v16, v0)
		Logf("[INVOKE] after: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_invoke_10")
		Logf("[INVOKE] before: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_invoke_11")
		func(s *user.Store[string]) {
			setup.BootstrapStore(s)
		}(v16)
		Logf("[INVOKE] after: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_invoke_11")
		Logf("[INVOKE] before: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_invoke_12")
		if err := dig_invoke_12(v16, v0, v1); err != nil {
			Logf("[INVOKE] failed: %s: %v\n", "github.com/shanjunmei/dig/example/app_debug.dig_invoke_12", err)
			return err
		}
		Logf("[INVOKE] after: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_invoke_12")
		Logf("[INVOKE] before: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_invoke_13")
		dig_invoke_13(v8)
		Logf("[INVOKE] after: %s\n", "github.com/shanjunmei/dig/example/app_debug.dig_invoke_13")
		return nil
	}
}
