// Code generated by digen; DO NOT EDIT.

//go:generate go run -mod=mod github.com/shanjunmei/dig/cmd/digen  -debug=false -unused=drop -alias=full -out=dig_gen.go
//go:build !digen
// +build !digen

package app_debug

import (
	"context"
	"fmt"
	"github.com/shanjunmei/dig/example/cache"
	"github.com/shanjunmei/dig/example/common"
	"github.com/shanjunmei/dig/example/db"
	"github.com/shanjunmei/dig/example/internal/logger"
	"github.com/shanjunmei/dig/example/role"
	role_repository "github.com/shanjunmei/dig/example/role/repository"
	"github.com/shanjunmei/dig/example/user"
	"github.com/shanjunmei/dig/example/user/repository"
)

func dig_provider_1() (str string, err error) {
	str = "user-module"
	return
}

func dig_provider_3() (primaryDB *db.DB, err error) {
	primaryDB = &db.DB{Name: "primary", DSN: "postgres://primary:5432/app"}
	return
}

func dig_provider_4() (replicaDB *db.DB, err error) {
	replicaDB = &db.DB{Name: "replica", DSN: "postgres://replica:5432/app"}
	return
}

func dig_provider_5() (userRedis *db.RedisClient) {
	userRedis = &db.RedisClient{Name: "user", Address: "redis://user:6379"}
	return
}

func dig_provider_6() (sessionRedis *db.RedisClient) {
	sessionRedis = &db.RedisClient{Name: "session", Address: "redis://session:6379"}
	return
}

func dig_provider_7() *user.Store[string] {
	s := user.NewStore[string]()
	s.Add("hello")
	s.Add("world")
	return s
}

func dig_invoke_1(r *repository.Repository[string]) {
	r.Print()
}

func dig_invoke_2(r *role_repository.Repository[int]) {
	r.Add(42)
	r.Print()
}

func dig_invoke_3(cfg role.Config) {
	fmt.Printf("Config supplied: %s\n", cfg)
}

func dig_invoke_4(s *role.Server) {
	s.Run()
}

func dig_invoke_5(stringCache *cache.Cache[string], intCache *cache.Cache[int]) {
	stringCache.Set("greeting", "hello")
	intCache.Set("count", 42)
	fmt.Println("Cache module:")
	stringCache.Print()
	intCache.Print()
}

func dig_invoke_6(primaryDB *db.DB, userRedis *db.RedisClient) {
	primaryDB.Ping()
	userRedis.Ping()
}

func dig_invoke_7(replicaDB *db.DB, sessionRedis *db.RedisClient) {
	fmt.Printf("Replica: %s, Session: %s\n", replicaDB.Name, sessionRedis.Name)
}

func dig_invoke_8(primaryDB *db.DB, userRedis *db.RedisClient) {
	primaryDB.Ping()
	userRedis.Ping()
}

func dig_invoke_9(s *user.Store[string], cfg *common.Config) {
	if cfg.Port > 8000 {
		s.Add("high-port")
	} else {
		s.Add("low-port")
	}
}

func dig_invoke_10(s *user.Store[string], cfg *common.Config, log *logger.Logger) error {
	log.Println("Debug App Invoke: store len =", len(s.GetAll()))
	return nil
}

func dig_invoke_11(stringCache *cache.Cache[string]) {
	stringCache.Set("from-debug", "cross-package")
	stringCache.Print()
}

func InitAppDebug(cfg *common.Config, log *logger.Logger) func(context.Context) error {
	v0 := cfg
	v1 := log
	v2 := user.NewStore[int]()
	v3 := repository.NewRepository[string]()
	v4, err := dig_provider_1()
	if err != nil {
		panic(err)
	}
	v5 := 100
	v6 := role_repository.NewRepository[int]()
	v7 := role.Config("production")
	v8 := cache.NewCache[string]()
	v9 := cache.NewCache[int]()
	v11, err := dig_provider_3()
	if err != nil {
		panic(err)
	}
	v12, err := dig_provider_4()
	if err != nil {
		panic(err)
	}
	v13 := dig_provider_5()
	v14 := dig_provider_6()
	v15 := dig_provider_7()
	v17 := role.NewServer(v5)
	return func(ctx context.Context) error {
		dig_invoke_1(v3)
		if err := user.ProcessStore[int](v2, v4); err != nil {
			return err
		}
		dig_invoke_2(v6)
		dig_invoke_3(v7)
		dig_invoke_4(v17)
		dig_invoke_5(v8, v9)
		dig_invoke_6(v11, v13)
		dig_invoke_7(v12, v14)
		dig_invoke_8(v11, v13)
		dig_invoke_9(v15, v0)
		if err := dig_invoke_10(v15, v0, v1); err != nil {
			return err
		}
		dig_invoke_11(v8)
		return nil
	}
}
