// Code generated by digen; DO NOT EDIT.

//go:generate go run -mod=mod github.com/shanjunmei/dig/cmd/digen  -debug=false -unused=ignore -alias=full -inline=true -out=dig_gen.go
//go:build !digen
// +build !digen

package closure_capture_exported

import (
	"context"
	"github.com/shanjunmei/dig/example/closure_exported_helper"
)

func dig_invoke_1() error {
	_ = closure_exported_helper.ExportedVar
	_ = closure_exported_helper.ExportedConst
	return nil
}

func InitCaptureExported() func(context.Context) error {
	_ = closure_exported_helper.NewConfig()
	return func(ctx context.Context) error {
		if err := dig_invoke_1(); err != nil {
			return err
		}
		return nil
	}
}
