// Code generated by digen; DO NOT EDIT.

//go:generate go run -mod=mod github.com/shanjunmei/dig/cmd/digen  -debug=false -unused=drop -alias=full -inline=false -out=dig_gen.go
//go:build !digen
// +build !digen

package app_edge

import (
	"context"
	"fmt"
	"github.com/shanjunmei/dig/example/cache"
	"github.com/shanjunmei/dig/example/common"
	"github.com/shanjunmei/dig/example/db"
	"github.com/shanjunmei/dig/example/internal/logger"
	"github.com/shanjunmei/dig/example/role"
	role_repository "github.com/shanjunmei/dig/example/role/repository"
	"github.com/shanjunmei/dig/example/setup"
	"github.com/shanjunmei/dig/example/user"
	"github.com/shanjunmei/dig/example/user/repository"
)

func dig_provider_1() (str string, err error) {
	str = "user-module"
	return
}

func dig_provider_3() (primaryDB *db.DB, err error) {
	primaryDB = &db.DB{Name: "primary", DSN: "postgres://primary:5432/app"}
	return
}

func dig_provider_4() (replicaDB *db.DB, err error) {
	replicaDB = &db.DB{Name: "replica", DSN: "postgres://replica:5432/app"}
	return
}

func dig_provider_5() (userRedis *db.RedisClient) {
	userRedis = &db.RedisClient{Name: "user", Address: "redis://user:6379"}
	return
}

func dig_provider_6() (sessionRedis *db.RedisClient) {
	sessionRedis = &db.RedisClient{Name: "session", Address: "redis://session:6379"}
	return
}

func dig_provider_7() *user.Store[string] {
	s := user.NewStore[string]()
	s.Add("hello")
	s.Add("world")
	return s
}

func dig_provider_10() common.Config {
	return common.Config{Addr: "127.0.0.1", Port: 9000}
}

func dig_provider_12() (closureDB *db.DB) {
	return &db.DB{Name: "inmem", DSN: "mem://"}
}

func dig_provider_14() *db.DB {
	return &db.DB{Name: "default", DSN: "postgres://default:5432/app"}
}

func dig_provider_8(primaryDB *db.DB) db.Pinger {
	return primaryDB
}

func dig_provider_9(primaryDB *db.DB) any {
	return any(primaryDB)
}

func dig_provider_11(cfg common.Config) (setupCfg *common.Config) {
	return &cfg
}

func dig_provider_13(closureDB *db.DB) db.DB {
	return *closureDB
}

func dig_invoke_1(r *repository.Repository[string]) {
	r.Print()
}

func dig_invoke_2(r *role_repository.Repository[int]) {
	r.Add(42)
	r.Print()
}

func dig_invoke_3(cfg role.Config) {
	fmt.Printf("Config supplied: %s\n", cfg)
}

func dig_invoke_4(s *role.Server) {
	s.Run()
}

func dig_invoke_5(stringCache *cache.Cache[string], intCache *cache.Cache[int]) {
	stringCache.Set("greeting", "hello")
	intCache.Set("count", 42)
	fmt.Println("Cache module:")
	stringCache.Print()
	intCache.Print()
}

func dig_invoke_6(primaryDB *db.DB, userRedis *db.RedisClient) {
	primaryDB.Ping()
	userRedis.Ping()
}

func dig_invoke_7(replicaDB *db.DB, sessionRedis *db.RedisClient) {
	fmt.Printf("Replica: %s, Session: %s\n", replicaDB.Name, sessionRedis.Name)
}

func dig_invoke_8(primaryDB *db.DB, userRedis *db.RedisClient) {
	primaryDB.Ping()
	userRedis.Ping()
}

func dig_invoke_9(pinger db.Pinger, raw any, setupCfg *common.Config, dbVal db.DB, closureDB *db.DB) {
	pinger.Ping()
	if d, ok := raw.(*db.DB); ok {
		d.Ping()
	}
	_ = setupCfg.Port
	_ = dbVal.Name
	closureDB.Ping()
}

func dig_invoke_10(s *user.Store[string], cfg *common.Config) {
	if cfg.Port > 8000 {
		s.Add("high-port")
	} else {
		s.Add("low-port")
	}
}

func dig_invoke_11(s *user.Store[string]) {
	setup.BootstrapStore(s)
}

func dig_invoke_12(defaultDB *db.DB, primaryDB *db.DB, log *logger.Logger) {
	log.Println("Edge: default DB =", defaultDB.Name, ", primary DB =", primaryDB.Name)
}

func dig_invoke_13(stringCache *cache.Cache[string], log *logger.Logger) {
	stringCache.Set("edge", "boundary-test")
	stringCache.Print()
}

func dig_invoke_14(cfg *common.Config, log *logger.Logger) error {
	log.Println("Edge: port =", cfg.Port)
	return nil
}

func InitAppEdge(cfg *common.Config, log *logger.Logger) func(context.Context) error {
	v0 := cfg
	v1 := log
	v2 := user.NewStore[int]()
	v3 := repository.NewRepository[string]()
	v4, err := dig_provider_1()
	if err != nil {
		panic(err)
	}
	v5 := 100
	v6 := role_repository.NewRepository[int]()
	v7 := role.Config("production")
	v8 := cache.NewCache[string]()
	v9 := cache.NewCache[int]()
	v11, err := dig_provider_3()
	if err != nil {
		panic(err)
	}
	v12, err := dig_provider_4()
	if err != nil {
		panic(err)
	}
	v13 := dig_provider_5()
	v14 := dig_provider_6()
	v15 := dig_provider_7()
	v16 := dig_provider_10()
	v17 := dig_provider_12()
	v18 := dig_provider_14()
	v19 := role.NewServer(v5)
	v20 := dig_provider_8(v11)
	v21 := dig_provider_9(v11)
	v22 := dig_provider_11(v16)
	v23 := dig_provider_13(v17)
	return func(ctx context.Context) error {
		dig_invoke_1(v3)
		if err := user.ProcessStore[int](v2, v4); err != nil {
			return err
		}
		dig_invoke_2(v6)
		dig_invoke_3(v7)
		dig_invoke_4(v19)
		dig_invoke_5(v8, v9)
		dig_invoke_6(v11, v13)
		dig_invoke_7(v12, v14)
		dig_invoke_8(v11, v13)
		dig_invoke_9(v20, v21, v22, v23, v17)
		dig_invoke_10(v15, v0)
		dig_invoke_11(v15)
		dig_invoke_12(v18, v11, v1)
		dig_invoke_13(v8, v1)
		if err := dig_invoke_14(v0, v1); err != nil {
			return err
		}
		return nil
	}
}
