// Code generated by digen; DO NOT EDIT.

//go:generate go run -mod=mod github.com/shanjunmei/dig/cmd/digen  -debug=true -unused=error -alias=full -inline=true -out=dig_gen.go
//go:build !digen
// +build !digen

package context_alias

import (
	ctx "context"
	"log"
)

var Logf = log.Printf

// closure defined at example/context_alias/di.go:16
func dig_invoke_1(c ctx.Context) {
}

func InitWithContextAlias() func(ctx.Context) error {
	return func(c ctx.Context) error {
		Logf("[INVOKE] before: %s\n", "github.com/shanjunmei/dig/example/context_alias.dig_invoke_1")
		dig_invoke_1(c)
		Logf("[INVOKE] after: %s\n", "github.com/shanjunmei/dig/example/context_alias.dig_invoke_1")
		return nil
	}
}
