// Code generated by digen; DO NOT EDIT.

//go:generate go run -mod=mod github.com/shanjunmei/dig/cmd/digen  -debug=false -unused=error -alias=full -inline=false -out=dig_gen.go
//go:build !digen
// +build !digen

package context_alias

import (
	ctx "context"
)

func dig_invoke_1(c ctx.Context) {
}

func InitWithContextAlias() func(ctx.Context) error {
	return func(c ctx.Context) error {
		dig_invoke_1(c)
		return nil
	}
}
