// Code generated by digen; DO NOT EDIT.

//go:generate go run -mod=mod github.com/shanjunmei/dig/cmd/digen  -debug=false -unused=ignore -alias=full -inline=true -out=dig_gen.go
//go:build !digen
// +build !digen

package closure_capture_string_const

import (
	"context"
)

func InitCaptureStringConst() func(context.Context) error {
	dv0 := NewConfig()
	return func(ctx context.Context) error {
		func(cfg *Config) {
			cfg.Font = "font:cjk"

		}(dv0)
		return nil
	}
}
