// Code generated by digen; DO NOT EDIT.

//go:generate go run -mod=mod github.com/shanjunmei/dig/cmd/digen  -debug=false -unused=ignore -alias=full -inline=true -out=dig_gen.go
//go:build !digen
// +build !digen

package app_xpkg_generic

import (
	"context"
	"fmt"
	"github.com/shanjunmei/dig/example/cache"
	"github.com/shanjunmei/dig/example/common"
)

func dig_invoke_1(cfgCache *cache.Cache[*common.Config], cfg *common.Config) error {
	cfgCache.Set("default", cfg)
	cached, ok := cfgCache.Get("default")
	if !ok {
		return fmt.Errorf("config not found in cache")
	}
	fmt.Printf("XGen: cached config addr=%s port=%d\n", cached.Addr, cached.Port)
	return nil
}

func InitXPkgGeneric() func(context.Context) error {
	dv0 := cache.NewCache[*common.Config]()
	dv1 := &common.Config{Addr: "0.0.0.0", Port: 8080}
	return func(ctx context.Context) error {
		if err := dig_invoke_1(dv0, dv1); err != nil {
			return err
		}
		return nil
	}
}
