// Code generated by digen; DO NOT EDIT.

//go:generate go run -mod=mod github.com/shanjunmei/dig/cmd/digen  -debug=false -unused=ignore -alias=full -inline=true -out=dig_gen.go
//go:build !digen
// +build !digen

package app

import (
	"context"
	"fmt"
	"github.com/shanjunmei/dig/example/cache"
	"github.com/shanjunmei/dig/example/common"
	"github.com/shanjunmei/dig/example/db"
	"github.com/shanjunmei/dig/example/internal/logger"
	"github.com/shanjunmei/dig/example/role"
	role_repository "github.com/shanjunmei/dig/example/role/repository"
	"github.com/shanjunmei/dig/example/setup"
	"github.com/shanjunmei/dig/example/user"
	"github.com/shanjunmei/dig/example/user/repository"
)

func dig_provider_1() (str string, err error) {
	str = "user-module"
	return
}

func dig_provider_2() *cache.Cache[bool] {
	c := cache.NewCache[bool]()
	c.Set("enabled", true)
	return c
}

func dig_provider_3() (primaryDB *db.DB, err error) {
	primaryDB = &db.DB{Name: "primary", DSN: "postgres://primary:5432/app"}
	return
}

func dig_provider_4() (replicaDB *db.DB, err error) {
	replicaDB = &db.DB{Name: "replica", DSN: "postgres://replica:5432/app"}
	return
}

func dig_provider_5() (userRedis *db.RedisClient) {
	userRedis = &db.RedisClient{Name: "user", Address: "redis://user:6379"}
	return
}

func dig_provider_6() (sessionRedis *db.RedisClient) {
	sessionRedis = &db.RedisClient{Name: "session", Address: "redis://session:6379"}
	return
}

func dig_provider_7() *user.Store[string] {
	s := user.NewStore[string]()
	s.Add("hello")
	s.Add("world")
	return s
}

func dig_provider_12() (closureDB *db.DB) {
	return &db.DB{Name: "inmem", DSN: "mem://"}
}

func dig_invoke_2(r *role_repository.Repository[int]) {
	r.Add(42)
	r.Print()
}

func dig_invoke_5(stringCache *cache.Cache[string], intCache *cache.Cache[int]) {
	stringCache.Set("greeting", "hello")
	intCache.Set("count", 42)
	fmt.Println("Cache module:")
	stringCache.Print()
	intCache.Print()
}

func dig_invoke_6(primaryDB *db.DB, userRedis *db.RedisClient, Index db.RedisDbIndex) {
	primaryDB.Ping()
	userRedis.Ping(Index)
}

func dig_invoke_8(primaryDB *db.DB, userRedis *db.RedisClient, Index db.RedisDbIndex) {
	primaryDB.Ping()
	userRedis.Ping(Index)
}

func dig_invoke_9(pinger db.Pinger, raw any, setupCfg *common.Config, dbVal db.DB, closureDB *db.DB) {
	pinger.Ping()
	if d, ok := raw.(*db.DB); ok {
		d.Ping()
	}
	_ = setupCfg.Port
	_ = dbVal.Name
	closureDB.Ping()
}

func dig_invoke_12(s *user.Store[string], cfg *common.Config, log *logger.Logger) error {
	log.Println("App Invoke: store len =", len(s.GetAll()))
	return nil
}

func dig_invoke_13(stringCache *cache.Cache[string]) {
	stringCache.Set("from-app", "cross-package")
	stringCache.Print()
}

func InitApp(cfg *common.Config, log *logger.Logger) func(context.Context) error {
	dv0 := cfg
	dv1 := log
	dv2 := user.NewStore[int]()
	dv3 := repository.NewRepository[string]()
	dv4, err := dig_provider_1()
	if err != nil {
		panic(err)
	}
	dv5 := 100
	dv6 := role_repository.NewRepository[int]()
	dv7 := role.Config("production")
	dv8 := cache.NewCache[string]()
	dv9 := cache.NewCache[int]()
	_ = dig_provider_2()
	dv11 := db.Index
	dv12, err := dig_provider_3()
	if err != nil {
		panic(err)
	}
	dv13, err := dig_provider_4()
	if err != nil {
		panic(err)
	}
	dv14 := dig_provider_5()
	dv15 := dig_provider_6()
	dv16 := dig_provider_7()
	dv17 := func() common.Config {
		return common.Config{Addr: "127.0.0.1", Port: 9000}
	}()
	dv18 := dig_provider_12()
	_ = "app-v2"
	dv20 := role.NewServer(dv5)
	dv21 := db.Pinger(dv12)
	dv22 := any(dv12)
	dv23 := &dv17
	dv24 := *dv18
	return func(ctx context.Context) error {
		func(r *repository.Repository[string]) {
			r.Print()
		}(dv3)
		if err := user.ProcessStore[int](dv2, dv4); err != nil {
			return err
		}
		dig_invoke_2(dv6)
		func(cfg role.Config) {
			fmt.Printf("Config supplied: %s\n", cfg)
		}(dv7)
		func(s *role.Server) {
			s.Run()
		}(dv20)
		dig_invoke_5(dv8, dv9)
		dig_invoke_6(dv12, dv14, dv11)
		func(replicaDB *db.DB, sessionRedis *db.RedisClient) {
			fmt.Printf("Replica: %s, Session: %s\n", replicaDB.Name, sessionRedis.Name)
		}(dv13, dv15)
		dig_invoke_8(dv12, dv14, dv11)
		dig_invoke_9(dv21, dv22, dv23, dv24, dv18)
		func(s *user.Store[string], cfg *common.Config) {
			if cfg.Port > 8000 {
				s.Add("high-port")
			} else {
				s.Add("low-port")
			}
		}(dv16, dv0)
		func(s *user.Store[string]) {
			setup.BootstrapStore(s)
		}(dv16)
		if err := dig_invoke_12(dv16, dv0, dv1); err != nil {
			return err
		}
		dig_invoke_13(dv8)
		return nil
	}
}
