// Code generated by digen; DO NOT EDIT.

//go:generate go run -mod=mod github.com/shanjunmei/dig/cmd/digen  -debug=false -unused=error -alias=full -inline=false -out=dig_gen.go
//go:build !digen
// +build !digen

package shadow_err

import (
	"context"
	err "github.com/shanjunmei/dig/example/shadow_err/pkg"
)

func dig_invoke_1(i1 *err.Item1, i2 *err.Item2) {
	_ = i1
	_ = i2
}

func InitShadowErr() func(context.Context) error {
	dv0, err2 := err.NewItem1()
	if err2 != nil {
		panic(err2)
	}
	dv1, err2 := err.NewItem2()
	if err2 != nil {
		panic(err2)
	}
	return func(ctx context.Context) error {
		dig_invoke_1(dv0, dv1)
		return nil
	}
}
