// Code generated by digen; DO NOT EDIT.

//go:generate go run -mod=mod github.com/shanjunmei/dig/cmd/digen  -debug=false -unused=ignore -alias=full -inline=true -out=dig_gen.go
//go:build !digen
// +build !digen

package gf_unused_provider

import (
	"context"
)

func InitUnusedProvider() func(context.Context) error {
	dv0 := newUsed()
	_ = newUnused()
	return func(ctx context.Context) error {
		func(u *Used) {
			_ = u
		}(dv0)
		return nil
	}
}
