// Code generated by digen; DO NOT EDIT.

//go:generate go run -mod=mod github.com/shanjunmei/dig/cmd/digen  -debug=false -unused=ignore -alias=full -inline=true -out=dig_gen.go
//go:build !digen
// +build !digen

package app_gen_test

import (
	"context"
	"github.com/shanjunmei/dig/example/common"
)

func InitGenTest() func(context.Context) error {
	dv0 := makeConfigHandler()
	return func(ctx context.Context) error {
		if err := func(handler func(*common.Config) error) error {
			return handler(&common.Config{Addr: "test", Port: 8080})
		}(dv0); err != nil {
			return err
		}
		return nil
	}
}
