package generator

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/shanjunmei/dig/internal/config"
	"github.com/shanjunmei/dig/internal/logger"
	"github.com/shanjunmei/dig/internal/model"
	"github.com/shanjunmei/dig/pkg/functional"
	"golang.org/x/tools/go/packages"
)

const tagBuild = model.TagBuild
const diPkgPath = model.DiPkgPath

// headerTemplate defines the fixed header for generated files.
const headerTemplate = `// Code generated by %s; DO NOT EDIT.

//go` + `:generate go run -mod=mod %s/cmd/%s %s
//go:build !%s
// +build !%s

package %s

`

// Generator holds dependencies for code generation.
type Generator struct {
	logger *logger.Logger
	cfg    *config.Config
}

// NewGenerator creates a new Generator instance.
func NewGenerator(logger *logger.Logger, cfg *config.Config) *Generator {
	return &Generator{logger: logger, cfg: cfg}
}

// WriteGeneratedCode generates code and writes it to the target file.
func (g *Generator) WriteGeneratedCode(pkg *packages.Package, target *model.GenTarget, nodes []model.Node, refCount map[string]int, importAliasMap, pkgAliasMap, pkgNameMap map[string]string, fset *token.FileSet) error {
	outFile := filepath.Base(target.File)
	code, err := g.GenerateCode(nodes, refCount, pkg.Name, target.FuncName, pkg.PkgPath, importAliasMap, pkgAliasMap, pkgNameMap, fset, target.Node.Type.Params, outFile)
	if err != nil {
		return err
	}
	return os.WriteFile(target.File, []byte(code), 0644)
}

// getPkgAlias returns the import alias for a package path.
func getPkgAlias(pkgPath string, importAliasMap map[string]string, aliasMap map[string]string, pkgNameMap map[string]string) string {
	if alias, ok := importAliasMap[pkgPath]; ok {
		return alias
	}
	if alias, ok := aliasMap[pkgPath]; ok {
		return alias
	}
	if name, ok := pkgNameMap[pkgPath]; ok {
		return name
	}
	// 理论上不会走到这里，仅作为兜底
	parts := strings.Split(pkgPath, "/")
	return parts[len(parts)-1]
}

// pickCtxParamName selects a context parameter name that does not conflict with
// the context package alias or any other package alias/name used in the generated code.
func pickCtxParamName(ctxAlias string, usedAliases map[string]bool) string {
	candidates := []string{"ctx", "c", "ctxVal", "diCtx", "ctxParam"}
	for _, name := range candidates {
		if name != ctxAlias && !usedAliases[name] {
			return name
		}
	}
	// All common names taken — generate a unique fallback
	for i := 1; ; i++ {
		name := fmt.Sprintf("ctx%d", i)
		if name != ctxAlias && !usedAliases[name] {
			return name
		}
	}
}

// writeImports writes the import block.
func writeImports(buf *bytes.Buffer, mainPkgPath string, importAliasMap map[string]string, pkgAliasMap map[string]string, pkgNameMap map[string]string, usedPkgs []string) {
	importMap := make(map[string]string)
	for _, pkgPath := range usedPkgs {
		if pkgPath == mainPkgPath || pkgPath == "" {
			continue
		}
		importMap[pkgPath] = getPkgAlias(pkgPath, importAliasMap, pkgAliasMap, pkgNameMap)
	}
	paths := functional.Keys(importMap)
	sort.Strings(paths)

	buf.WriteString("import (\n")
	for _, path := range paths {
		alias := importMap[path]
		defaultName := pkgNameMap[path]
		if defaultName == "" {
			defaultName = alias
		}
		// 用户源码显式指定了 alias，必须保留
		if _, ok := importAliasMap[path]; ok {
			fmt.Fprintf(buf, "%s %q\n", alias, path)
			continue
		}

		if alias == defaultName {
			fmt.Fprintf(buf, "%q\n", path)
		} else {
			fmt.Fprintf(buf, "%s %q\n", alias, path)
		}
	}
	buf.WriteString(")\n\n")
}

// writeHeader writes the file header using the template.
func (g *Generator) writeHeader(buf *bytes.Buffer, pkgName string, outFile string) {
	params := g.buildExecParams(outFile)
	fmt.Fprintf(buf, headerTemplate, tagBuild, diPkgPath, tagBuild, params, tagBuild, tagBuild, pkgName)
}

// shouldGenerateProvider determines whether a provider should be generated.
func shouldGenerateProvider(node model.Node, refCount map[string]int, unusedMode model.UnusedMode) bool {
	if unusedMode != model.UnusedModeDrop {
		return true
	}
	return refCount[node.Name] > 0 || node.HasError
}

// writeClosureDefs writes closure provider definitions when needed.
func writeClosureDefs(buf *bytes.Buffer, nodes []model.Node, refCount map[string]int, unusedMode model.UnusedMode) {
	for _, node := range nodes {
		if !node.IsClosure || node.ClosureDef == "" {
			continue
		}
		// Phase 3: Skip closures that will be inlined as IIFE
		if node.ShouldInline {
			continue
		}
		// Phase 4: Skip identity closures (will use direct type conversion)
		if node.IsIdentityClosure {
			continue
		}
		if node.IsInvoke || shouldGenerateProvider(node, refCount, unusedMode) {
			fmt.Fprintf(buf, "%s\n\n", node.ClosureDef)
		}
	}
	if len(nodes) > 0 {
		buf.WriteString("\n")
	}
}

func (g *Generator) buildExecParams(outFile string) string {
	return fmt.Sprintf(" -debug=%v -unused=%s -alias=%s -inline=%v -out=%s", g.cfg.Debug, g.cfg.UnusedMode, g.cfg.AliasType, g.cfg.InlineClosures, outFile)
}

// GenerateCode generates the complete Go source code as a string.
func (g *Generator) GenerateCode(nodes []model.Node, refCount map[string]int, pkgName, originFuncName, mainPkgPath string, importAliasMap, pkgAliasMap, pkgNameMap map[string]string, fset *token.FileSet, params *ast.FieldList, outFile string) (string, error) {
	mainPkg := pkgName
	if mainPkg == "" {
		mainPkg = "main"
	}
	buf := &bytes.Buffer{}

	g.writeHeader(buf, mainPkg, outFile)

	usedPkgSet := make(map[string]bool, len(nodes)+1)
	usedPkgSet["context"] = true
	if g.cfg.Debug {
		usedPkgSet["log"] = true
	}
	for _, node := range nodes {
		if node.PkgPath != "" && node.PkgPath != mainPkgPath {
			usedPkgSet[node.PkgPath] = true
		}
		for _, pkgPath := range node.UsedPkgs {
			usedPkgSet[pkgPath] = true
		}
	}
	usedPkgs := functional.Keys(usedPkgSet)

	writeImports(buf, mainPkgPath, importAliasMap, pkgAliasMap, pkgNameMap, usedPkgs)
	if g.cfg.Debug {
		logPkgPath := "log"
		alias := getPkgAlias(logPkgPath, importAliasMap, pkgAliasMap, pkgNameMap)
		usedPkgSet[logPkgPath] = true
		fmt.Fprintf(buf, "var Logf = %s.Printf\n\n", alias)
	}

	writeClosureDefs(buf, nodes, refCount, g.cfg.UnusedMode)
	g.writeMainFunc(buf, nodes, originFuncName, g.cfg.UnusedMode, refCount, params, fset, importAliasMap, pkgAliasMap, pkgNameMap)

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return "", fmt.Errorf("formatting generated code failed: %w\nraw code:\n%s", err, buf.String())
	}
	return string(formatted), nil
}

// formatParams formats the function parameters for the generated function signature.
func formatParams(params *ast.FieldList, fset *token.FileSet) string {
	if params == nil || len(params.List) == 0 {
		return ""
	}
	var buf bytes.Buffer
	for i, field := range params.List {
		if i > 0 {
			buf.WriteString(", ")
		}
		for j, name := range field.Names {
			if j > 0 {
				buf.WriteString(", ")
			}
			buf.WriteString(name.Name)
		}
		buf.WriteString(" ")
		if err := printer.Fprint(&buf, fset, field.Type); err != nil {
			panic(err) // should never happen
		}
	}
	return buf.String()
}

// isLiteral 判断字符串是否为 Go 字面量（数字、字符串、布尔、nil）
func isLiteral(s string) bool {
	if s == "true" || s == "false" || s == "nil" {
		return true
	}
	// 数字：整数、浮点数、复数
	if _, err := strconv.ParseFloat(s, 64); err == nil {
		return true
	}
	// 字符串：以 " 或 ` 开头
	if strings.HasPrefix(s, `"`) || strings.HasPrefix(s, "`") {
		return true
	}
	return false
}

// emitLog writes a debug log statement if debug mode is enabled.
func (g *Generator) emitLog(buf *bytes.Buffer, format string, args ...string) {
	if !g.cfg.Debug {
		return
	}
	if !strings.HasSuffix(format, "\n") {
		format += "\n"
	}
	buf.WriteString("Logf(")
	buf.WriteString(strconv.Quote(format))
	for _, arg := range args {
		buf.WriteString(", ")
		buf.WriteString(arg)
	}
	buf.WriteString(")\n")
}

// buildIIFECall converts a ClosureDef to an IIFE form.
// ClosureDef: "func name(params) returns body"
// Returns:    "func(params) returns body(args)"
func buildIIFECall(node model.Node) string {
	if !node.ShouldInline || node.ClosureDef == "" {
		return ""
	}
	// Strip the function name: "func name(params)..." -> "func(params)..."
	def := node.ClosureDef
	// Find the opening paren ( after the function name
	idx := strings.Index(def, "(")
	if idx < 0 {
		return def
	}
	// Find "func " prefix to skip the name
	funcPrefix := strings.Index(def, "func ")
	if funcPrefix < 0 {
		return def
	}
	// "func name" length is the distance from "func " to the opening paren
	// Replace "func name" with "func"
	paramsStart := idx
	// Skip everything from "func " to "("
	return "func" + def[paramsStart:]
}

// buildIdentityConversion 根据 node 中的信息生成内联表达式字符串
// ctxParamName 是调用上下文中的变量名（即实参表达式）
func buildIdentityConversion(node model.Node, ctxParamName string) string {
	if !node.IsIdentityClosure {
		return ""
	}
	switch node.IdentityOp {
	case model.OpDirect:
		return fmt.Sprintf("%s(%s)", node.IdentityTargetType, ctxParamName)
	case model.OpAddr:
		return fmt.Sprintf("&%s", ctxParamName)
	case model.OpDeref:
		return fmt.Sprintf("*%s", ctxParamName)
	case model.OpConvert:
		return fmt.Sprintf("%s(%s)", node.IdentityTargetType, ctxParamName)
	default:
		return ""
	}
}

// buildCallArgs builds the argument list for a function call from node.Args.
// Const args are skipped since they're inlined as literals in the closure body.
func buildCallArgs(node model.Node, ctxParamName string) []string {
	var args []string
	for _, arg := range node.Args {
		if arg.IsContext {
			args = append(args, ctxParamName)
		} else if arg.IsConst {
			// Phase 1: Const values are inlined in the body, skip in call
			continue
		} else {
			args = append(args, arg.Name)
		}
	}
	return args
}

// writeProvider writes a single provider statement.
// If blank is true, the result is assigned to '_' (unused provider).
func (g *Generator) writeProvider(buf *bytes.Buffer, node model.Node, blank bool, ctxParamName string) {
	if node.IsSupply {
		expr := node.Value
		if node.FuncPkg != "" && !isLiteral(expr) && !strings.HasPrefix(expr, node.FuncPkg+".") {
			expr = node.FuncPkg + "." + expr
		}
		g.emitLog(buf, "[SUPPLY] before: %s", strconv.Quote(node.RetType))
		if node.Comment != "" {
			fmt.Fprintf(buf, "\t%s\n", node.Comment)
		}
		if blank {
			fmt.Fprintf(buf, "_ = %s\n", expr)
		} else {
			fmt.Fprintf(buf, "%s := %s\n", node.Name, expr)
		}
		g.emitLog(buf, "[SUPPLY] after: %s", strconv.Quote(node.RetType))
		return
	}

	logName := node.LongName()

	// Phase 4: Identity closure - use direct type conversion
	if node.IsIdentityClosure {
		identityArgs := buildCallArgs(node, ctxParamName)
		identityParam := ctxParamName
		if len(identityArgs) > 0 {
			identityParam = identityArgs[0]
		}
		conversion := buildIdentityConversion(node, identityParam)
		g.emitLog(buf, "[PROVIDE] identity conversion: %s -> %s", strconv.Quote(logName), node.IdentityTargetType)
		if blank {
			fmt.Fprintf(buf, "_ = %s\n", conversion)
		} else {
			fmt.Fprintf(buf, "%s := %s\n", node.Name, conversion)
		}
		g.emitLog(buf, "[PROVIDE] after: %s", strconv.Quote(logName))
		return
	}

	args := buildCallArgs(node, ctxParamName)
	argsStr := strings.Join(args, ", ")

	var fullCall string
	if node.IsClosure {
		if node.ShouldInline {
			fullCall = buildIIFECall(node)
		} else {
			fullCall = node.Func
		}
	} else {
		fullCall = model.FullFuncName(node.FuncPkg, node.Func) + node.GenericArgs
	}

	g.emitLog(buf, "[PROVIDE] before: %s", strconv.Quote(logName))

	if blank {
		if node.HasError {
			// 有error返回，即使结果不用，依然校验错误并panic，保持行为统一
			fmt.Fprintf(buf, "if _, err := %s(%s); err != nil {\n", fullCall, argsStr)
			g.emitLog(buf, "[PROVIDE] failed (unused): %s: %v", strconv.Quote(logName), "err")
			fmt.Fprintf(buf, "panic(err)\n}\n")
		} else {
			fmt.Fprintf(buf, "_ = %s(%s)\n", fullCall, argsStr)
		}
	} else {
		if node.HasError {
			fmt.Fprintf(buf, "%s, err := %s(%s)\n", node.Name, fullCall, argsStr)
			fmt.Fprintf(buf, "if err != nil {\n")
			g.emitLog(buf, "[PROVIDE] failed: %s: %v", strconv.Quote(logName), "err")
			fmt.Fprintf(buf, "panic(err)\n}\n")
		} else {
			fmt.Fprintf(buf, "%s := %s(%s)\n", node.Name, fullCall, argsStr)
		}
	}

	g.emitLog(buf, "[PROVIDE] after: %s", strconv.Quote(logName))
}

// writeProviders writes all provider statements.
func (g *Generator) writeProviders(buf *bytes.Buffer, nodes []model.Node, refCount map[string]int, unusedMode model.UnusedMode, ctxParamName string) {
	for _, node := range nodes {
		if node.IsInvoke {
			continue
		}
		if !shouldGenerateProvider(node, refCount, unusedMode) {
			continue
		}
		blank := false
		if !node.HasError && refCount[node.Name] == 0 && unusedMode == model.UnusedModeIgnore {
			blank = true
		}
		g.writeProvider(buf, node, blank, ctxParamName)
	}
}

// writeInvokes writes all invoke statements.
func (g *Generator) writeInvokes(buf *bytes.Buffer, nodes []model.Node, ctxParamName string) {
	for _, node := range nodes {
		if !node.IsInvoke {
			continue
		}
		logName := node.LongName()

		// Phase 4: Identity closure - use direct type conversion
		if node.IsIdentityClosure {
			identityArgs := buildCallArgs(node, ctxParamName)
			identityParam := ctxParamName
			if len(identityArgs) > 0 {
				identityParam = identityArgs[0]
			}
			conversion := buildIdentityConversion(node, identityParam)
			g.emitLog(buf, "[INVOKE] identity conversion: %s -> %s", strconv.Quote(logName), node.IdentityTargetType)
			if node.HasError {
				fmt.Fprintf(buf, "if err := %s; err != nil {\n", conversion)
				g.emitLog(buf, "[INVOKE] failed: %s: %v", strconv.Quote(logName), "err")
				fmt.Fprintf(buf, "return err\n}\n")
			} else {
				fmt.Fprintf(buf, "%s\n", conversion)
			}
			g.emitLog(buf, "[INVOKE] after: %s", strconv.Quote(logName))
			continue
		}

		args := buildCallArgs(node, ctxParamName)
		argsStr := strings.Join(args, ", ")

		var fullCall string
		if node.IsClosure {
			if node.ShouldInline {
				fullCall = buildIIFECall(node)
			} else {
				fullCall = node.Func
			}
		} else {
			fullCall = model.FullFuncName(node.FuncPkg, node.Func) + node.GenericArgs
		}

		g.emitLog(buf, "[INVOKE] before: %s", strconv.Quote(logName))

		if node.HasError {
			fmt.Fprintf(buf, "if err := %s(%s); err != nil {\n", fullCall, argsStr)
			g.emitLog(buf, "[INVOKE] failed: %s: %v", strconv.Quote(logName), "err")
			fmt.Fprintf(buf, "return err\n}\n")
		} else {
			fmt.Fprintf(buf, "%s(%s)\n", fullCall, argsStr)
		}

		g.emitLog(buf, "[INVOKE] after: %s", strconv.Quote(logName))
	}
}

// writeMainFunc writes the main generated function.
func (g *Generator) writeMainFunc(buf *bytes.Buffer, nodes []model.Node, originFuncName string, unusedMode model.UnusedMode, refCount map[string]int, params *ast.FieldList, fset *token.FileSet, importAliasMap, pkgAliasMap, pkgNameMap map[string]string) {
	paramStr := formatParams(params, fset)
	if paramStr != "" {
		paramStr = " " + paramStr
	}
	ctxAlias := getPkgAlias("context", importAliasMap, pkgAliasMap, pkgNameMap)
	// Pick a parameter name that does not shadow any package alias used in the generated code.
	// Try conventional names first, fall back to less common ones.
	usedAliases := make(map[string]bool, len(importAliasMap)+len(pkgAliasMap)+len(pkgNameMap))
	for _, a := range importAliasMap {
		usedAliases[a] = true
	}
	for _, a := range pkgAliasMap {
		usedAliases[a] = true
	}
	for _, a := range pkgNameMap {
		usedAliases[a] = true
	}
	ctxParam := pickCtxParamName(ctxAlias, usedAliases)
	fmt.Fprintf(buf, "func %s(%s) func(%s.Context) error {\n", originFuncName, paramStr, ctxAlias)
	g.writeProviders(buf, nodes, refCount, unusedMode, ctxParam)
	fmt.Fprintf(buf, "\treturn func(%s %s.Context) error {\n", ctxParam, ctxAlias)
	g.writeInvokes(buf, nodes, ctxParam)
	buf.WriteString("\t\treturn nil\n\t}\n}\n\n")
}
