package generator

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/printer"
	"go/token"
	"os"
	"sort"
	"strconv"
	"strings"

	"github.com/shanjunmei/dig/internal/config"
	"github.com/shanjunmei/dig/internal/logger"
	"github.com/shanjunmei/dig/internal/model"
	"github.com/shanjunmei/dig/pkg/functional"
	"golang.org/x/tools/go/packages"
)

const tagBuild = model.TagBuild
const diPkgPath = model.DiPkgPath

type Generator struct {
	logger *logger.Logger
	cfg    *config.Config
}

func NewGenerator(logger *logger.Logger, cfg *config.Config) *Generator {
	return &Generator{logger: logger, cfg: cfg}
}

// WriteGeneratedCode 生成并写入文件
func (g *Generator) WriteGeneratedCode(pkg *packages.Package, target *model.GenTarget, nodes []model.Node, refCount map[string]int, pkgAliasMap map[string]string, fset *token.FileSet) error {
	code, err := g.GenerateCode(nodes, refCount, pkg.Name, target.FuncName, pkg.PkgPath, pkgAliasMap, fset, target.Node.Type.Params)
	if err != nil {
		return err
	}
	return os.WriteFile(target.File, []byte(code), 0644)
}

func writeImports(buf *bytes.Buffer, mainPkgPath string, pkgAliasMap map[string]string, usedPkgs []string) {
	importMap := make(map[string]string)
	for _, pkgPath := range usedPkgs {
		if pkgPath == mainPkgPath || pkgPath == "" {
			continue
		}
		alias, ok := pkgAliasMap[pkgPath]
		if !ok {
			parts := strings.Split(pkgPath, "/")
			alias = parts[len(parts)-1]
		}
		importMap[pkgPath] = alias
	}
	paths := functional.Keys(importMap)
	sort.Strings(paths)

	buf.WriteString("import (\n")
	for _, path := range paths {
		alias := importMap[path]
		parts := strings.Split(path, "/")
		defaultName := parts[len(parts)-1]
		if alias == defaultName {
			fmt.Fprintf(buf, "%q\n", path)
		} else {
			fmt.Fprintf(buf, "%s %q\n", alias, path)
		}
	}
	buf.WriteString(")\n\n")
}

func writeHeader(buf *bytes.Buffer, pkgName string) {
	fmt.Fprintf(buf, "// Code generated by %s; DO NOT EDIT.\n\n", tagBuild)
	fmt.Fprintf(buf, "//go:generate go run -mod=mod %s/cmd/%s\n", diPkgPath, tagBuild)
	fmt.Fprintf(buf, "//go:build !%s\n", tagBuild)
	fmt.Fprintf(buf, "// +build !%s\n\n", tagBuild)
	fmt.Fprintf(buf, "package %s\n\n", pkgName)
}

func writeClosureDefs(buf *bytes.Buffer, nodes []model.Node, refCount map[string]int, unusedMode model.UnusedMode) {
	for _, node := range nodes {
		if !node.IsClosure || node.ClosureDef == "" {
			continue
		}
		if node.IsInvoke {
			fmt.Fprintf(buf, "%s\n", node.ClosureDef)
			continue
		}
		if shouldGenerateProvider(node, refCount, unusedMode) {
			fmt.Fprintf(buf, "%s\n", node.ClosureDef)
		}
	}
	if len(nodes) > 0 {
		buf.WriteString("\n")
	}
}

func shouldGenerateProvider(node model.Node, refCount map[string]int, unusedMode model.UnusedMode) bool {
	if unusedMode != model.UnusedModeDrop {
		return true
	}
	return refCount[node.Name] > 0 || node.HasError
}

// GenerateCode 生成代码字符串
func (g *Generator) GenerateCode(nodes []model.Node, refCount map[string]int, pkgName, originFuncName, mainPkgPath string, pkgAliasMap map[string]string, fset *token.FileSet, params *ast.FieldList) (string, error) {
	mainPkg := pkgName
	if mainPkg == "" {
		mainPkg = "main"
	}
	buf := &bytes.Buffer{}

	writeHeader(buf, mainPkg)

	usedPkgSet := make(map[string]bool, len(nodes)+1)
	usedPkgSet["context"] = true
	if g.cfg.Debug {
		usedPkgSet["log"] = true
	}
	for _, node := range nodes {
		if node.PkgPath != "" && node.PkgPath != mainPkgPath {
			usedPkgSet[node.PkgPath] = true
		}
		for _, pkgPath := range node.UsedPkgs {
			usedPkgSet[pkgPath] = true
		}
	}
	usedPkgs := functional.Keys(usedPkgSet)

	writeImports(buf, mainPkgPath, pkgAliasMap, usedPkgs)
	if g.cfg.Debug {
		buf.WriteString("var Logf = log.Printf\n\n")
	}

	writeClosureDefs(buf, nodes, refCount, g.cfg.UnusedMode)
	g.writeMainFunc(buf, nodes, originFuncName, g.cfg.UnusedMode, refCount, params, fset)

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return "", fmt.Errorf("formatting generated code failed: %w\nraw code:\n%s", err, buf.String())
	}
	return string(formatted), nil
}

func formatParams(params *ast.FieldList, fset *token.FileSet) string {
	if params == nil || len(params.List) == 0 {
		return ""
	}
	var buf bytes.Buffer
	for i, field := range params.List {
		if i > 0 {
			buf.WriteString(", ")
		}
		for j, name := range field.Names {
			if j > 0 {
				buf.WriteString(", ")
			}
			buf.WriteString(name.Name)
		}
		buf.WriteString(" ")
		if err := printer.Fprint(&buf, fset, field.Type); err != nil {
			panic(err) // 实际可返回错误，但此处简化
		}
	}
	return buf.String()
}

func (g *Generator) emitLog(buf *bytes.Buffer, format string, args ...string) {
	if !g.cfg.Debug {
		return
	}
	if !strings.HasSuffix(format, "\n") {
		format += "\n"
	}
	buf.WriteString("Logf(")
	buf.WriteString(strconv.Quote(format))
	for _, arg := range args {
		buf.WriteString(", ")
		buf.WriteString(arg)
	}
	buf.WriteString(")\n")
}

// ---------- 使用 node.Args 代替旧字段 ----------
func (g *Generator) handleUnusedProvider(buf *bytes.Buffer, node model.Node) {
	logName := node.LongName()
	if node.IsSupply {
		expr := node.Value
		if node.FuncPkg != "" && !strings.HasPrefix(expr, node.FuncPkg+".") {
			expr = node.FuncPkg + "." + expr
		}
		g.emitLog(buf, "[SUPPLY] before: supply %s", strconv.Quote(logName))
		fmt.Fprintf(buf, "_ = %s\n", expr)
		g.emitLog(buf, "[SUPPLY] after:  %s", strconv.Quote(logName))
	} else if node.IsClosure {
		argNames := make([]string, len(node.Args))
		for i, arg := range node.Args {
			argNames[i] = arg.Name
		}
		argsStr := strings.Join(argNames, ", ")
		g.emitLog(buf, "[PROVIDE] before: %s", strconv.Quote(logName))
		fmt.Fprintf(buf, "_ = %s(%s)\n", node.Func, argsStr)
		g.emitLog(buf, "[PROVIDE] after: %s", strconv.Quote(logName))
	} else {
		full := model.FullFuncName(node.FuncPkg, node.Func)
		argNames := make([]string, len(node.Args))
		for i, arg := range node.Args {
			argNames[i] = arg.Name
		}
		argsStr := strings.Join(argNames, ", ")
		g.emitLog(buf, "[PROVIDE] before: %s", strconv.Quote(logName))
		fmt.Fprintf(buf, "_ = %s(%s)\n", full, argsStr)
		g.emitLog(buf, "[PROVIDE] after: %s", strconv.Quote(logName))
	}
}

// ---------- buildCallArgs 从 model.Arg 读取 ----------
func buildCallArgs(node model.Node) []string {
	args := make([]string, len(node.Args))
	for i, arg := range node.Args {
		if arg.IsContext {
			args[i] = "ctx"
		} else {
			args[i] = arg.Name
		}
	}
	return args
}

func (g *Generator) writeProviderStatement(buf *bytes.Buffer, node model.Node) {
	if node.IsSupply {
		expr := node.Value
		if node.FuncPkg != "" && !strings.HasPrefix(expr, node.FuncPkg+".") {
			expr = node.FuncPkg + "." + expr
		}
		g.emitLog(buf, "[SUPPLY] before:  %s", strconv.Quote(node.RetType))
		fmt.Fprintf(buf, "%s := %s\n", node.Name, expr)
		g.emitLog(buf, "[SUPPLY] after:  %s", strconv.Quote(node.RetType))
		return
	}

	callName := node.ShortName()
	logName := node.LongName()
	args := buildCallArgs(node)
	argsStr := strings.Join(args, ", ")

	g.emitLog(buf, "[PROVIDE] before: %s", strconv.Quote(logName))

	if node.IsClosure {
		fmt.Fprintf(buf, "%s := %s(%s)\n", node.Name, node.Func, argsStr)
		g.emitLog(buf, "[PROVIDE] after: %s", strconv.Quote(logName))
		return
	}

	if node.HasError {
		fmt.Fprintf(buf, "%s, err := %s(%s)\n", node.Name, callName, argsStr)
		fmt.Fprintf(buf, "if err != nil {\n")
		g.emitLog(buf, "[PROVIDE] failed: %s: %v", strconv.Quote(logName), "err")
		fmt.Fprintf(buf, "panic(err)\n}\n")
	} else {
		fmt.Fprintf(buf, "%s := %s(%s)\n", node.Name, callName, argsStr)
	}

	g.emitLog(buf, "[PROVIDE] after: %s", strconv.Quote(logName))
}

func (g *Generator) writeProviders(buf *bytes.Buffer, nodes []model.Node, refCount map[string]int, unusedMode model.UnusedMode) {
	for _, node := range nodes {
		if node.IsInvoke {
			continue
		}
		if !shouldGenerateProvider(node, refCount, unusedMode) {
			continue
		}
		if !node.HasError && refCount[node.Name] == 0 {
			if unusedMode == model.UnusedModeIgnore {
				g.handleUnusedProvider(buf, node)
				continue
			}
		}
		g.writeProviderStatement(buf, node)
	}
}

func (g *Generator) writeInvokes(buf *bytes.Buffer, nodes []model.Node) {
	for _, node := range nodes {
		if !node.IsInvoke {
			continue
		}
		callName := node.ShortName()
		logName := node.LongName()
		args := buildCallArgs(node)
		argsStr := strings.Join(args, ", ")

		g.emitLog(buf, "[INVOKE] before: %s", strconv.Quote(logName))

		if node.IsClosure {
			if node.HasError {
				fmt.Fprintf(buf, "if err := %s(%s); err != nil {\n", node.Func, argsStr)
				g.emitLog(buf, "[INVOKE] failed: %s: %v", strconv.Quote(logName), "err")
				fmt.Fprintf(buf, "return err\n}\n")
			} else {
				fmt.Fprintf(buf, "%s(%s)\n", node.Func, argsStr)
			}
		} else {
			if node.HasError {
				fmt.Fprintf(buf, "if err := %s(%s); err != nil {\n", callName, argsStr)
				g.emitLog(buf, "[INVOKE] failed: %s: %v", strconv.Quote(logName), "err")
				fmt.Fprintf(buf, "return err\n}\n")
			} else {
				fmt.Fprintf(buf, "%s(%s)\n", callName, argsStr)
			}
		}

		g.emitLog(buf, "[INVOKE] after: %s", strconv.Quote(logName))
	}
}

func (g *Generator) writeMainFunc(buf *bytes.Buffer, nodes []model.Node, originFuncName string, unusedMode model.UnusedMode, refCount map[string]int, params *ast.FieldList, fset *token.FileSet) {
	paramStr := formatParams(params, fset)
	if paramStr != "" {
		paramStr = " " + paramStr // 前导空格
	}
	fmt.Fprintf(buf, "func %s(%s) func(context.Context) error {\n", originFuncName, paramStr)
	g.writeProviders(buf, nodes, refCount, unusedMode)
	fmt.Fprintf(buf, "\treturn func(ctx context.Context) error {\n")
	g.writeInvokes(buf, nodes)
	buf.WriteString("\t\treturn nil\n\t}\n}\n\n")
}
