package generator

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/printer"
	"go/token"
	"os"
	"sort"
	"strconv"
	"strings"

	"github.com/shanjunmei/dig/internal/config"
	"github.com/shanjunmei/dig/internal/logger"
	"github.com/shanjunmei/dig/internal/model"
	"github.com/shanjunmei/dig/pkg/functional"
	"golang.org/x/tools/go/packages"
)

const tagBuild = model.TagBuild
const diPkgPath = model.DiPkgPath

// headerTemplate defines the fixed header for generated files.
const headerTemplate = `// Code generated by %s; DO NOT EDIT.

//go:generate go run -mod=mod %s/cmd/%s
//go:build !%s
// +build !%s

package %s

`

// Generator holds dependencies for code generation.
type Generator struct {
	logger *logger.Logger
	cfg    *config.Config
}

// NewGenerator creates a new Generator instance.
func NewGenerator(logger *logger.Logger, cfg *config.Config) *Generator {
	return &Generator{logger: logger, cfg: cfg}
}

// WriteGeneratedCode generates code and writes it to the target file.
func (g *Generator) WriteGeneratedCode(pkg *packages.Package, target *model.GenTarget, nodes []model.Node, refCount map[string]int, pkgAliasMap map[string]string, fset *token.FileSet) error {
	code, err := g.GenerateCode(nodes, refCount, pkg.Name, target.FuncName, pkg.PkgPath, pkgAliasMap, fset, target.Node.Type.Params)
	if err != nil {
		return err
	}
	return os.WriteFile(target.File, []byte(code), 0644)
}

// getPkgAlias returns the import alias for a package path.
func getPkgAlias(pkgPath string, aliasMap map[string]string) string {
	if alias, ok := aliasMap[pkgPath]; ok {
		return alias
	}
	parts := strings.Split(pkgPath, "/")
	return parts[len(parts)-1]
}

// writeImports writes the import block.
func writeImports(buf *bytes.Buffer, mainPkgPath string, pkgAliasMap map[string]string, usedPkgs []string) {
	importMap := make(map[string]string)
	for _, pkgPath := range usedPkgs {
		if pkgPath == mainPkgPath || pkgPath == "" {
			continue
		}
		importMap[pkgPath] = getPkgAlias(pkgPath, pkgAliasMap)
	}
	paths := functional.Keys(importMap)
	sort.Strings(paths)

	buf.WriteString("import (\n")
	for _, path := range paths {
		alias := importMap[path]
		parts := strings.Split(path, "/")
		defaultName := parts[len(parts)-1]
		if alias == defaultName {
			fmt.Fprintf(buf, "%q\n", path)
		} else {
			fmt.Fprintf(buf, "%s %q\n", alias, path)
		}
	}
	buf.WriteString(")\n\n")
}

// writeHeader writes the file header using the template.
func writeHeader(buf *bytes.Buffer, pkgName string) {
	fmt.Fprintf(buf, headerTemplate, tagBuild, diPkgPath, tagBuild, tagBuild, tagBuild, pkgName)
}

// shouldGenerateProvider determines whether a provider should be generated.
func shouldGenerateProvider(node model.Node, refCount map[string]int, unusedMode model.UnusedMode) bool {
	if unusedMode != model.UnusedModeDrop {
		return true
	}
	return refCount[node.Name] > 0 || node.HasError
}

// writeClosureDefs writes closure provider definitions when needed.
func writeClosureDefs(buf *bytes.Buffer, nodes []model.Node, refCount map[string]int, unusedMode model.UnusedMode) {
	for _, node := range nodes {
		if !node.IsClosure || node.ClosureDef == "" {
			continue
		}
		if node.IsInvoke || shouldGenerateProvider(node, refCount, unusedMode) {
			fmt.Fprintf(buf, "%s\n", node.ClosureDef)
		}
	}
	if len(nodes) > 0 {
		buf.WriteString("\n")
	}
}

// GenerateCode generates the complete Go source code as a string.
func (g *Generator) GenerateCode(nodes []model.Node, refCount map[string]int, pkgName, originFuncName, mainPkgPath string, pkgAliasMap map[string]string, fset *token.FileSet, params *ast.FieldList) (string, error) {
	mainPkg := pkgName
	if mainPkg == "" {
		mainPkg = "main"
	}
	buf := &bytes.Buffer{}

	writeHeader(buf, mainPkg)

	usedPkgSet := make(map[string]bool, len(nodes)+1)
	usedPkgSet["context"] = true
	if g.cfg.Debug {
		usedPkgSet["log"] = true
	}
	for _, node := range nodes {
		if node.PkgPath != "" && node.PkgPath != mainPkgPath {
			usedPkgSet[node.PkgPath] = true
		}
		for _, pkgPath := range node.UsedPkgs {
			usedPkgSet[pkgPath] = true
		}
	}
	usedPkgs := functional.Keys(usedPkgSet)

	writeImports(buf, mainPkgPath, pkgAliasMap, usedPkgs)
	if g.cfg.Debug {
		buf.WriteString("var Logf = log.Printf\n\n")
	}

	writeClosureDefs(buf, nodes, refCount, g.cfg.UnusedMode)
	g.writeMainFunc(buf, nodes, originFuncName, g.cfg.UnusedMode, refCount, params, fset)

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return "", fmt.Errorf("formatting generated code failed: %w\nraw code:\n%s", err, buf.String())
	}
	return string(formatted), nil
}

// formatParams formats the function parameters for the generated function signature.
func formatParams(params *ast.FieldList, fset *token.FileSet) string {
	if params == nil || len(params.List) == 0 {
		return ""
	}
	var buf bytes.Buffer
	for i, field := range params.List {
		if i > 0 {
			buf.WriteString(", ")
		}
		for j, name := range field.Names {
			if j > 0 {
				buf.WriteString(", ")
			}
			buf.WriteString(name.Name)
		}
		buf.WriteString(" ")
		if err := printer.Fprint(&buf, fset, field.Type); err != nil {
			panic(err) // should never happen
		}
	}
	return buf.String()
}

// isIdentOrSelector 判断字符串是否为合法的 Go 标识符或选择器表达式
func isIdentOrSelector(s string) bool {
	if len(s) == 0 {
		return false
	}
	// 首字符必须是字母或下划线
	if (s[0] < 'a' || s[0] > 'z') && (s[0] < 'A' || s[0] > 'Z') && s[0] != '_' {
		return false
	}
	for _, c := range s {
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_' || c == '.' {
			continue
		}
		return false
	}
	return true
}

// emitLog writes a debug log statement if debug mode is enabled.
func (g *Generator) emitLog(buf *bytes.Buffer, format string, args ...string) {
	if !g.cfg.Debug {
		return
	}
	if !strings.HasSuffix(format, "\n") {
		format += "\n"
	}
	buf.WriteString("Logf(")
	buf.WriteString(strconv.Quote(format))
	for _, arg := range args {
		buf.WriteString(", ")
		buf.WriteString(arg)
	}
	buf.WriteString(")\n")
}

// buildCallArgs builds the argument list for a function call from node.Args.
func buildCallArgs(node model.Node) []string {
	args := make([]string, len(node.Args))
	for i, arg := range node.Args {
		if arg.IsContext {
			args[i] = "ctx"
		} else {
			args[i] = arg.Name
		}
	}
	return args
}

// writeProvider writes a single provider statement.
// If blank is true, the result is assigned to '_' (unused provider).
func (g *Generator) writeProvider(buf *bytes.Buffer, node model.Node, blank bool) {
	if node.IsSupply {
		expr := node.Value
		if node.FuncPkg != "" && isIdentOrSelector(expr) && !strings.HasPrefix(expr, node.FuncPkg+".") {
			expr = node.FuncPkg + "." + expr
		}
		g.emitLog(buf, "[SUPPLY] before: %s", strconv.Quote(node.RetType))
		if blank {
			fmt.Fprintf(buf, "_ = %s\n", expr)
		} else {
			fmt.Fprintf(buf, "%s := %s\n", node.Name, expr)
		}
		g.emitLog(buf, "[SUPPLY] after: %s", strconv.Quote(node.RetType))
		return
	}

	logName := node.LongName()
	args := buildCallArgs(node)
	argsStr := strings.Join(args, ", ")

	var fullCall string
	if node.IsClosure {
		fullCall = node.Func
	} else {
		fullCall = model.FullFuncName(node.FuncPkg, node.Func) + node.GenericArgs
	}

	g.emitLog(buf, "[PROVIDE] before: %s", strconv.Quote(logName))

	if blank {
		fmt.Fprintf(buf, "_ = %s(%s)\n", fullCall, argsStr)
	} else {
		if node.HasError {
			fmt.Fprintf(buf, "%s, err := %s(%s)\n", node.Name, fullCall, argsStr)
			fmt.Fprintf(buf, "if err != nil {\n")
			g.emitLog(buf, "[PROVIDE] failed: %s: %v", strconv.Quote(logName), "err")
			fmt.Fprintf(buf, "panic(err)\n}\n")
		} else {
			fmt.Fprintf(buf, "%s := %s(%s)\n", node.Name, fullCall, argsStr)
		}
	}

	g.emitLog(buf, "[PROVIDE] after: %s", strconv.Quote(logName))
}

// writeProviders writes all provider statements.
func (g *Generator) writeProviders(buf *bytes.Buffer, nodes []model.Node, refCount map[string]int, unusedMode model.UnusedMode) {
	for _, node := range nodes {
		if node.IsInvoke {
			continue
		}
		if !shouldGenerateProvider(node, refCount, unusedMode) {
			continue
		}
		blank := false
		if !node.HasError && refCount[node.Name] == 0 && unusedMode == model.UnusedModeIgnore {
			blank = true
		}
		g.writeProvider(buf, node, blank)
	}
}

// writeInvokes writes all invoke statements.
func (g *Generator) writeInvokes(buf *bytes.Buffer, nodes []model.Node) {
	for _, node := range nodes {
		if !node.IsInvoke {
			continue
		}
		args := buildCallArgs(node)
		argsStr := strings.Join(args, ", ")
		logName := node.LongName()

		var fullCall string
		if node.IsClosure {
			fullCall = node.Func
		} else {
			fullCall = model.FullFuncName(node.FuncPkg, node.Func) + node.GenericArgs
		}

		g.emitLog(buf, "[INVOKE] before: %s", strconv.Quote(logName))

		if node.HasError {
			fmt.Fprintf(buf, "if err := %s(%s); err != nil {\n", fullCall, argsStr)
			g.emitLog(buf, "[INVOKE] failed: %s: %v", strconv.Quote(logName), "err")
			fmt.Fprintf(buf, "return err\n}\n")
		} else {
			fmt.Fprintf(buf, "%s(%s)\n", fullCall, argsStr)
		}

		g.emitLog(buf, "[INVOKE] after: %s", strconv.Quote(logName))
	}
}

// writeMainFunc writes the main generated function.
func (g *Generator) writeMainFunc(buf *bytes.Buffer, nodes []model.Node, originFuncName string, unusedMode model.UnusedMode, refCount map[string]int, params *ast.FieldList, fset *token.FileSet) {
	paramStr := formatParams(params, fset)
	if paramStr != "" {
		paramStr = " " + paramStr
	}
	fmt.Fprintf(buf, "func %s(%s) func(context.Context) error {\n", originFuncName, paramStr)
	g.writeProviders(buf, nodes, refCount, unusedMode)
	fmt.Fprintf(buf, "\treturn func(ctx context.Context) error {\n")
	g.writeInvokes(buf, nodes)
	buf.WriteString("\t\treturn nil\n\t}\n}\n\n")
}
