// Code generated by digen; DO NOT EDIT.

//go:generate go run -mod=mod github.com/shanjunmei/dig/cmd/digen  -debug=false -unused=ignore -alias=full -inline=true -out=dig_gen.go
//go:build !digen
// +build !digen

package shadow_freevar

import (
	"context"
	"github.com/shanjunmei/dig/example/db"
	"github.com/shanjunmei/dig/example/shadow_freevar/helper"
)

func dig_provider_1(db_fv *helper.Counter) *helper.Result {
	return &helper.Result{Value: db_fv.Count}
}

func dig_invoke_1(r *helper.Result, d *db.DB) {
	_ = r
	_ = d
}

func InitShadowFreeVar() func(context.Context) error {
	dv0 := &helper.Counter{Count: 42}
	dv1 := &db.DB{Name: "test"}
	dv2 := dig_provider_1(dv0)
	return func(ctx context.Context) error {
		dig_invoke_1(dv2, dv1)
		return nil
	}
}
