// Code generated by digen; DO NOT EDIT.

//go:generate go run -mod=mod github.com/shanjunmei/dig/cmd/digen  -debug=false -unused=ignore -alias=full -inline=true -out=dig_gen.go
//go:build !digen
// +build !digen

package closure_param

import (
	"context"
	"fmt"
	"github.com/shanjunmei/dig/example/closure_param_helper"
)

func InitClosureParam() func(context.Context) error {
	dv0 := closure_param_helper.NewConfigFactory()
	return func(ctx context.Context) error {
		func(f func() closure_param_helper.Config) {
			fmt.Println("invoked closure param:", f())
		}(dv0)
		return nil
	}
}
